config/routes.rb
Reports::Application.routes.draw do
  authenticated :user do
    root :to => 'reports#index'
  end

  devise_scope :user do
    root :to => "devise/sessions#new"
  end

  devise_for :users
  resources :users
  resources :reports
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :reporter
      can :create, Report
      can :read, Report, user_id: user.id
    end
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :active, :description, :name, :created_at
  belongs_to :user
  validates :name, presence: true
  paginates_per 5

  class << self
    def sort_by(column, direction)
      order_column = Report.column_names.include?(column) ? column : 'created_at'
      direction = %w(asc desc).include?(direction) ? direction : 'desc'
      order(order_column + ' ' + direction)
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :reports

  before_create :set_default_role

  private
  def set_default_role
    self.add_role :reporter
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  load_and_authorize_resource
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.includes(:user).sort_by(params[:sort], params[:direction]).page params[:page]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = current_user.reports.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
  def sort_to(column)
    direction = (params[:sort] == column && params[:direction] == 'desc') ? 'asc' : 'desc'
    link_to(column.capitalize, { sort: column, direction: direction }, class: params[:sort] == column ? direction : nil)
  end
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class=("alert alert-#{name == :notice ? "success" : "error"}") 
      a.close data-dismiss="alert"  ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
= link_to "Reports", root_path, :class => 'brand'
ul.nav
  - if user_signed_in?
    li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      li
        = link_to 'Admin', users_path
  - else
    li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="width=device-width, initial-scale=1.0" name="viewport" 
      title= content_for?(:title) ? yield(:title) : "Reports"
      meta content=(content_for?(:description) ? yield(:description) : "Reports") name="description" 
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  body class=("#{controller_name} #{action_name}") 
    .navbar.navbar-fixed-top
      nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main role="main" 
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          footer
      /! ! end of .container
    /! ! end of #main

app/views/reports/_form.html.slim
= simple_form_for(@report) do |f|
  = f.input :name, input_html: { class: 'input-xxlarge' }
  = f.input :description, input_html: { class: 'input-xxlarge' }
  label.checkbox
    | Active
    = f.check_box :active
  = f.button :submit, "Save report", :class => 'btn-primary'

app/views/reports/edit.html.slim
h3 Editing report
= render 'form'
= link_to 'Show', @report, class: 'btn btn-success'
| &nbsp;
= link_to 'Back', reports_path, class: 'btn'

app/views/reports/index.html.slim
h3 Listing reports

table.table.table-hover
  thead
    tr
      th = sort_to 'name'
      th = sort_to 'description'
      th = sort_to 'active'
      th = sort_to 'user'
      th
      th
      th
  tbody
    - @reports.each do |report|
      tr
        td = report.name
        td = report.description
        td = report.active
        td =  link_to report.user.name, report.user
        td = link_to 'Show', report, class: 'btn btn-mini btn-success'
        td = link_to 'Edit', edit_report_path(report), class: 'btn btn-mini btn-primary'
        td = link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger'
= paginate @reports

= link_to 'New Report', new_report_path, class: 'btn btn-success'

app/views/reports/new.html.slim
h3 New report
= render 'form'
= link_to 'Back', reports_path, class: 'btn'

app/views/reports/show.html.slim
h3 Report
dl.dl-horizontal
  dt Name:
  dd = best_in_place @report, :name
  dt Description:
  dd = best_in_place @report, :description, type: :textarea
  dt Active:
  dd = best_in_place @report, :active, type: :checkbox, :collection => ['True', 'False']
= link_to 'Edit', edit_report_path(@report), class: 'btn btn-primary'
| &nbsp;
= link_to 'Back', reports_path, class: 'btn'

app/views/users/_user.html.slim
.modal id="role-options-#{user.id}" style=("display: none;") 
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      a.close data-dismiss="modal"  ×
      h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      a.btn data-dismiss="modal" href="#"  Close

app/views/users/index.html.slim
h3 Users
table.table.table-hover
  thead
    tr
      th Username
      th Email
      th Registered
      th Role
      th
      th
  tbody
    - @users.each do |user|
      tr
        td= link_to user.name, user
        td= user.email
        td= user.created_at.to_date
        td= user.roles.first.name.titleize unless user.roles.first.nil?
        td
          a.btn.btn-mini data-toggle="modal" href="#role-options-#{user.id}" type="button"  Change role
          = render user
        td= link_to("Delete user", user_path(user), :data =>   confirm=("Are you sure?" ) , :method => :delete, :class => 'btn btn-mini btn-danger') unless user == current_user

app/views/users/show.html.slim
h3 User
p
  | User: #{@user.name}
p
  | Email: #{@user.email if @user.email}